trigger:
- 'main'

pool:
  name: 'VM-agent'

steps:


- task: AzureCLI@2
  displayName: show Azure CLI version and account information
  inputs:
    azureSubscription: azure-cli-2022-03-15-08-33-56
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az --version
      az account show


- task: AzureCLI@2
  displayName: Initialize terraform repo
  inputs:
    azureSubscription: 'azure-cli-2022-03-15-08-33-56'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: pwd && terraform init 
    workingDirectory: './terraform'
    


- task: AzureCLI@2
  displayName: Make terraform plan
  inputs:
    azureSubscription: azure-cli-2022-03-15-08-33-56
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: terraform apply
    workingDirectory: './terraform'
    addSpnToEnvironment: true
