trigger:
- none

pool:
  name: 'VM-agent'

steps:
- task: Bash@3
  inputs:
    targetType: filePath
    filePath: ./JMeter-command-to-run.sh
    
- task: Bash@3
  inputs:
    targetType: inline
    script: 
      git config --global user.email "niels.deen@devoteam.com";
      git config --global user.name "Niels Deen";
      git checkout -t origin/main
      git add .;
      git commit -m "added JMeter test results to repository";
      git push origin main;
