trigger:
- none

pool:
  name: 'VM-agent'

steps:
- task: Bash@3
  inputs:
    targetType: filePath
    filePath: ./JMeter-command-to-run.sh
    
- task: Bash@3
  inputs:
    targetType: inline
    script: 
      git config --global user.email "niels.deen@devoteam.com";
      git config --global user.name "Niels Deen";
      echo "CURRENT DIRECTORY:";
      pwd;
      git checkout origin/main;
      echo "CHECKOUT DONE";
      git add .;
      echo "ADD COMMAND DONE";
      git commit -m "added JMeter test results to repository";
      echo "COMMIT COMMAND DONE";
      git rebase HEAD main
      echo "REBASE DONE"
      git push origin main;
      echo "PUSH DONE"
