trigger:
- 'main'

pool:
  name: 'VM-agent'

steps:


- task: AzureCLI@2
  displayName: show Azure CLI version and account information
  inputs:
    azureSubscription: azure-cli-2022-03-15-08-33-56
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az --version
      az account show


- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure-cli-2022-03-15-08-33-56'
    scriptType: 'batch'
    scriptLocation: 'inlineScript'
    inlineScript: 'terraform init'
    workingDirectory: './terraform'