schedules:
- cron: "0 11 * * *"
  displayName: Triggered once a day
  branches:
    include:
    - '*'

pr: none
trigger: none

pool:
  name: 'VM-agent'

steps:

- task: Bash@3
  inputs:
    targetType: inline
    script:
      echo "Removing all previous JMeter results.." &&
      pwd &&
      sudo rm -R ./loadtest/dashboard ;
      mkdir ./loadtest/dashboard ;
      sudo rm -R ./loadtest/test_log ;
      mkdir ./loadtest/test_log ;
      echo "Done." ;
      echo "test print"

- task: Bash@3
  inputs:
    targetType: filePath
    filePath: ./JMeter-command-to-run.sh
    
- task: Bash@3
  inputs:
    targetType: inline
    script: 
      git config --global user.email "niels.deen@devoteam.com" &&
      git config --global user.name "Niels Deen" &&
      echo "CURRENT DIRECTORY:" &&
      pwd &&
      git add . &&
      echo "GIT STATUS" &&
      git status &&
      echo "ADD COMMAND DONE" &&
      git checkout -b "JMeter-branch" &&
      git commit -m "[skip azurepipelines]" &&
      echo "COMMIT COMMAND DONE" &&
      git remote set-url origin git@github.com:njjdeen/petclinic_testing.git &&
      git push -u origin JMeter-branch &&
      echo "PUSH DONE to JMeter branch, GO TO GITHUB AND MAKE MERGE REQUEST"
