trigger:
- none

pool:
  name: 'VM-agent'

steps:
- task: Bash@3
  inputs:
    targetType: filePath
    filePath: ./JMeter-command-to-run.sh
    
- task: Bash@3
  inputs:
    targetType: inline
    script: 
      git config --global user.email "niels.deen@devoteam.com" &&
      git config --global user.name "Niels Deen" &&
      echo "CURRENT DIRECTORY:" &&
      pwd &&
      git add . &&
      echo "GIT STATUS" &&
      git status &&
      echo "ADD COMMAND DONE" &&
      git checkout -b "JMeter-branch" &&
      git commit -m "added JMeter test results to repository" &&
      echo "COMMIT COMMAND DONE" &&
      git remote -v &&
      git push -u origin JMeter-branch &&
      echo "PUSH DONE to JMeter branch"
