trigger:
- '*'

pool:
  name: 'VM-agent'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'package'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'deploy'
    mavenOptions: '-DskipTests'

- task: Bash@3
  inputs:
    targetType: inline
    script: 
      pwd &&
      pip install selenium ;
      python3 selenium_test.py &&
      echo "Selenium test SUCCEEDED"
      