trigger:
- 'main'

pool:
  name: 'VM-agent'

steps:


- task: AzureCLI@2
  displayName: Azure CLI
  inputs:
    azureSubscription: azure-cli-2022-03-15-08-33-56
    scriptType: ps
    scriptLocation: inlineScript
    inlineScript: |
      az --version
      az account show