trigger:
- '*'

pool:
  name: 'VM-agent'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'package'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'deploy'
    mavenOptions: '-DskipTests'