resource_group_name         = "pers-niels_deen-rg"
resource_group_location     = "West Europe"
virtual_network_name        = "vnettest"
subnet_name                 = "subnettest"
public_ip_name              = "publiciptest"
network_security_group_name = "nsgtest"
network_interface_name      = "nictest"
linux_virtual_machine_name  = "linuxvmtest"