---
- name: "build new petclinic docker image"
  hosts: localhost
  connection: local
  tasks:

  - name: Remove previously built images if there are any
    community.docker.docker_image:
      state: absent
      name: nde01/petclinic:latest
   
  - name: Build an image and push it to docker hub
    community.docker.docker_image:
      name: nde01/petclinic:latest
      build:
        path: ../
      repository: nde01/petclinic:latest
      force_tag: yes
      push: yes
      source: build