---
- name: "stop petclinic docker container"
  hosts: all
  user: VMadmin
  tasks:

  - name: Remove all images
    become: yes
    docker_image:
      name: nde01/petclinic:latest
      state: absent