---
- name: "run petclinic docker container"
  hosts: all
  user: VMadmin
  tasks:
    
    - name: Start container with command
      become: yes
      docker_container:
        name: Petclinic_container
        image: nde01/petclinic:latest
        command: mvn package cargo:run -Dmaven.test.skip=true
        published_ports: 0.0.0.0:8080:9999