---
- name: "stop petclinic docker container"
  hosts: all
  user: VMadmin
  tasks:

  - name: Stop a container
    become: yes
    docker_container:
      name: Petclinic_container
      state: stopped